module.exports = {
  navBarLogo: require('./resources/asc-logos.png'),
  iStock: require('./resources/iStock.png'),
  iStock_1: require('./resources/iStock_1.png'),
  iStock_2: require('./resources/iStock_2.png'),
  top: require('./resources/top.png'),
  fb: require('./resources/fb.png'),
  tw: require('./resources/tw.png'),
  phone: require('./resources/phone.png'),
  app_store: require('./resources/app_store.png'),
  android_store: require('./resources/android_store.png'),
  profileImage: require('./resources/profilePhoto.jpg'),
  //kitesufr: require('./resources/kitesurf.jpg'),
  motocross: require('./resources/motocross.jpg'),
  mtnbike: require('./resources/mtnbike.jpg'),
  skate: require('./resources/skate.jpg'),
  snowboard: require('./resources/snowboard.jpg'),
  lorempixel1: require('./resources/lorempixel1.jpeg'),
  lorempixel2: require('./resources/lorempixel2.jpeg'),
  lorempixel3: require('./resources/lorempixel3.jpeg'),
  lorempixel4: require('./resources/lorempixel4.jpeg'),
  lorempixel5: require('./resources/lorempixel5.jpeg'),
  surf: require('./resources/surf.jpg')
};
